pywal/templates/colors--nodim-alacritty.yml, pywal/templates/colors-alacritty.yml
@sonjiku 's alacritty templates.
will gib a check to [#611](https://github.com/dylanaraps/pywal/pull/611) and diff that template from the one in this branch before merging.
=> alacritty templates

pywal/wallpaper.py
Reverts eylles/pywal16#10
merging that to the release tag branch was the wrong decision, it should be merged to master.
=> Revert "Adding support for gnome dark mode wallpapers"

pywal/templates/colors-leftwm-theme.ron
As suggested in [PyWal #688](https://github.com/dylanaraps/pywal/issues/688) here is a template for creating a `theme.ron`.
It was tested a couple of weeks ago with original `pywal`, except the `background_color` which is [a new feature](https://github.com/leftwm/leftwm/pull/922) that is expected to become merged by the end of the week.
@arcolinux could you give this another test spin?
Edit: also worth noting, the `background_color` will go unseen in almost any use cases, but I thought it might make sense to style all available color fields.
=> Add template for leftwm `theme.ron`

CHANGELOG.md, README.md, pywal/settings.py, pywal/wallpaper.py
preparing for release 3.4.0
~~update the wiki~~ this can be done AFTER releasing 
maybe i should put the CI in github itself, then upload to pypi
=> Release 3.4.0

pywal/templates/colors--nodim-alacritty.yml, pywal/templates/colors-alacritty.yml
As of Alacritty release 0.11.0, the syntax for setting the color of the bar changed from being nested under search to being it's own item "footer_bar". This fix matches the current Alacritty syntax and should remove the warning popup from Alacritty when loading the old style config.
Reference:
- [old config](https://github.com/alacritty/alacritty/blob/v0.10.1/alacritty.yml)
- [new config](https://github.com/alacritty/alacritty/blob/v0.11.0/alacritty.yml)
=> Change alacritty template to match v0.11.0+ config

pywal/wallpaper.py
pull request [#711](https://github.com/dylanaraps/pywal/pull/711)
@madstone0-0 just an interesting pattern i noticed both swaybg and swww take precedence before feh, my first thought is that is because a wayland environment could expect to find feh as part of xwayland and try to set the wallpaper there instead of where it should be setting it, no need to answer was just something i thought.
=> Added swaybg support

pywal/__main__.py, pywal/colors.py
@SaitoWu rebuilt the pr to just add the new behaviour and keep the old one as default, will test some before merging.
=> brighter colors

pywal/colors.py, pywal/theme.py, pywal/util.py, tests/test_colors.py, tests/test_files/test_file3.json, tests/test_util.py
Added generation and comparison of wallpaper checksums, cached in generated color schemes to allow for scheme regeneration on the contents of an image changing, which was brought up in issue [#692](https://github.com/dylanaraps/pywal/issues/692)
=> Added wallpaper checksum generation and comparison for cached color schemes 

pywal/util.py
For example when a terminal is suspended by Flow Control. Tested on Linux with Konsole and Kitty with suspend mode (Crtl+S) enabled
This is an attempt to get around https://github.com/eylles/pywal16/issues/22
=> Open file in non-blocking mode to skip write-blocked TTYs

pywal/backends/modern_colorthief.py
Discussed in https://github.com/eylles/pywal16/discussions/43#discussioncomment-9439870
=> Add support for modern colorthief

pywal/sequences.py
sending to /dev/pts/0 leads to a erronious notification on KDE plasma. not breaking, but annoying.
adds a check to not do that when the DE is "plasma", addition of other DEs with the problem welcome
=> fix empty message on plasma

pywal/sequences.py, pywal/util.py
could not find a way to do non blocking io checks with portalocker the way it can be done with fcntl, this should address #49
=> No fcntl on unsupported platform

pywal/colors.py
this is so that when you generate a 16 cols scheme you get `<image name>_16_lighten_...` or `<image name>_16_darken_...` and you don't have the issue of generating with one method, then generating with the other and pywal choosing the cached colorscheme made with the wrong method.
=> add cols16 method when generating 16 cols

pywal/__main__.py, pywal/colors.py, pywal/settings.py
Love the idea in https://github.com/eylles/pywal16/pull/62, but the merged version didn't seem to do anything upon testing, so worked through the bugs we found. This is our first contribution to this repo, so if we've done anything wrong or in bad style, we'd appreciate the feedback.
Also bumped the cache version since the new  cache matching format is expressly incompatible with the old one.
As a side note, the colours generated by increased contrast ratio bug us quite a bit, since increased luminance (and decreased saturation) tend to make what would be distinct colours look nearly the same.  It might be wiser to, if a majority of colours come up short in desired_luminance, to darken the background and lighten the foreground instead of acting on each colour separately.
=> make contrast actually do something

README.md, setup.py
Allow pywal16 to be used immediately after install, without manual setup and post-installation step(s).
=> Add (optional) dependencies to setup.py

pywal/util.py
The constrast calculations use imagemagick on their backend to get the average color of the image, this ensures the operation can be done in systems that got imagemagick 6.
=> Support im6

pywal/__main__.py, pywal/backends/colorthief.py, pywal/backends/colorz.py, pywal/backends/fast_colorthief.py, pywal/backends/haishoku.py, pywal/backends/modern_colorthief.py, pywal/backends/okthief.py, pywal/backends/schemer2.py, pywal/backends/wal.py, pywal/colors.py
This ought to address #77
@deviantfero please check that this suffices for the needs of wpgtk
=> Use kwargs for cols16 and contrast

pywal/util.py
@Ciavi i find interest in this, please elaborate is this intended to be used with the `-a` flag in some manner?
=> adjust_alpha

tests/test_export.py
pytest failed in the latest 3.7.0
```
> =========================== short test summary info ============================
> FAILED tests/test_export.py::TestExportColors::test_all_templates - KeyError: 'checksum'
> FAILED tests/test_export.py::TestExportColors::test_css_template - KeyError: 'checksum'
```
Both tests in `test_export.py` use `export.every()`, and the function call chain is as followed:
https://github.com/eylles/pywal16/blob/784d0b9aaec945478342601258626372baae806b/tests/test_export.py#L41
https://github.com/eylles/pywal16/blob/784d0b9aaec945478342601258626372baae806b/pywal/export.py#L120-L122
https://github.com/eylles/pywal16/blob/784d0b9aaec945478342601258626372baae806b/pywal/export.py#L75-L85
#79 added exporting checksum in `flatten_colors()`, which requires that the …
=> Missing checksum in test_file.json caused pytest to fail

pywal/colors.py
This should ideally make the API more compatible as we can produce the same format of colorscheme name that legacy pywal produces when none of the pywal16 exclusive flags are passed.
this should address #92
=> Change cache_fname cols16 and contrast handling

pywal/export.py
i've been wanting something like #66 for a while.
my use case specifically is qbittorrent-themes.
they need a file called `config.json` (by that specific name) which is pretty generic.
i _could_ post-process filenames before i run it through `rcc`, but i thought it would be nice for pywal16 to support child directories inside the template folder instead. 
this way i can organize my qbittorrent-stuff and have room for more `config.json` files that might be needed for other programs.
the PR introduces a naive class which contains every reference needed to read templates and output them to the correct spot. this could also just be a tuple, or a dictionary or something if you prefer that.
`walk` is a super simple function that leverages `os.path` stuff. i went with a generator-type of …
=> support nested directories in template directories

pywal/__main__.py
Hello
Recently, I made a fresh installation of Linux Mint (specifically Linux Mint 21.2 Victoria) on my machine, and I installed `pywal16` using `pip3`. Everything was going fine until I tried to execute it with the `wal`  command, and I and got this error.
```
Traceback (most recent call last):
File "/home/josh/.local/bin/wal", line 5, in <module>
from pywal.__main__ import main
File "/home/josh/.local/lib/python3.10/site-packages/pywal/__main__.py", line 21, in <module>
colorama.just_fix_windows_console()  # NOOP for non-Windows
AttributeError: module 'colorama' has no attribute 'just_fix_windows_console'
```
As the error says, python couldn’t find any function related to the `colorama` library. And after doing some research, I found that #70 introduced some changes to the code for …
=> Fix colorama import to restrict usage to Windows systems only

pywal/templates/colors-wal-dwm.h
dwm and dmenu are very often used together and thus should share the same palette. Favouring dmenu's selection bg colour over dwm's is mostly arbitrary. I think dmenu's (color1) tends to look better, and [rofi uses it as well](https://github.com/eylles/pywal16/blob/master/pywal/templates/colors-rofi-light.rasi#L16) so there's some precedent.
What's most important is that they match.
=> Change dwm selection bg colour to match dmenu's

pywal/templates/colors-fuzzel.ini, pywal/templates/colors-mako, pywal/templates/colors-tofi, pywal/templates/colors-zathura
This commit adds templates for the following programs: [fuzzel](https://codeberg.org/dnkl/fuzzel), [mako](https://github.com/emersion/mako), [tofi](https://github.com/philj56/tofi) and [zathura](https://github.com/pwmt/zathura). All of these can be imported/included to your already existing configurations.
Add `include=/home/amolinae/.cache/wal/colors-mako` to your mako configuration.
**NOTE:** requires [this commit](https://github.com/emersion/mako/commit/4d48aca5f3c92d9c01282cd40b8d3b2c959bdac6) for it to work.
Add `include /home/youruser/.cache/wal/colors-zathura` to your zathurarc.
**NOTE:** This template changes the page color to match with your colorscheme.
Add `include = include = ~/.cache/wal/colors-fuzzel.ini` to your fuzzel configuration.
Add `include = …
=> Add templates for fuzzel, mako, tofi, and zathura

pywal/templates/colors-retroarch.cfg
you will need to set ```menu_driver = "rgui"```, ```rgui_menu_color_theme = "0"``` and ```rgui_menu_theme_preset = "~/.cache/wal/colors-retroarch.cfg"``` in your retroarch config
=> retroarch rgui template

pywal/theme.py
Previously util.Color's class variable alpha_num was set only when the user supplied an alpha value on the command line. This meant that functions using it (namely alpha_hex and alpha_dec) used the default alpha_num value of 100 any time the user specified a JSON/YAML theme file (as opposed to manually specifying an alpha value with command-line flag -a).
=> Set alpha_num even when user specifies theme file

pywal/__main__.py
The warning is issued on windows when the current TERMINAL is not one of the terminal emulators that do not require the just_fix_windows_console function.
this should fix #150 without affecting other platforms like linux, mac or bsd.
=> Warn when colorama is not present on windows

pywal/__main__.py, pywal/colors.py, pywal/theme.py, pywal/util.py
Since 2122595ae32f649120133263b8316ee1a744847b the alpha being passed with `-a` was no longer respected. I have tested manually somewhat and the pytests passed, but might be worth a look over.
=> Prefer passed alpha over theme alpha

pywal/backends/wal.py
I decided to switch to animated (GIF) wallpapers today, using the default 'wal' backend, and pywal16 couldn't generate a colorscheme for any GIF I tried.
This commit makes the hexadecimal color regex more specific, and only tried to extract the whole match when the regex actually matched; it now works with all GIFs I tried.
=> Parse ImageMagick output more reliably

pywal/colors.py, pywal/util.py
this should modify the internal behaviour of the saturation flag so that it is more intuitive as it now adds the passed value onto the color's saturation instead of replacing it.
=> Change behaviour of --saturate flag
