pywal/reload.py
PR [#595](https://github.com/dylanaraps/pywal/pull/595)
=> Pass socket as an argument if reloading kitty from outside

pywal/sequences.py
[#510](https://github.com/dylanaraps/pywal/pull/510)
@cornett can you confirm this works as intended in this fork? i mean there shouldn't be a reason why it doesn't but i preffer to play it safe since i don't got an openbsd machine to confirm by myself.
=> Set terminal colors on OpenBSD

pywal/wallpaper.py
pull request [#669](https://github.com/dylanaraps/pywal/pull/669) from @Almamu
will test this later.
=> Empty cache fix

pywal/wallpaper.py
pull request [#681](https://github.com/dylanaraps/pywal/pull/681)
will merge later
=> Adding support for gnome dark mode wallpapers

pywal/util.py
some extra modifiers for the color vars for higher flexibility.
more to come.
=> new props (1)

pywal/wallpaper.py
pull request [#681](https://github.com/dylanaraps/pywal/pull/681)
=> Support gnome dark mode wallpapers 

pywal/wallpaper.py
Reverts eylles/pywal16#14
oh god, this was so stupid, i should remember to NEVER again merge this kind of stuff to the branch for the release PR.
=> Revert "Revert "Adding support for gnome dark mode wallpapers""

pywal/templates/colors-rgb
pull request [#706](https://github.com/dylanaraps/pywal/pull/706)
@TheWisker
=> added rgb color template

pywal/wallpaper.py
pull request [#703](https://github.com/dylanaraps/pywal/pull/703)
@Colepng
i think i can merge this one just fine
=> Add support for swww

pywal/__main__.py
pull request [#709](https://github.com/dylanaraps/pywal/pull/709)
@chriskingio
=> Enable wallpaper overrides when using a theme

pywal/wallpaper.py
pull request [#708](https://github.com/dylanaraps/pywal/pull/708)
@Gremious
=> Use bytestring for wallpaper path on Windows

pywal/export.py
pull request [#725](https://github.com/dylanaraps/pywal/pull/725)
@masonesl this is a simple fix so i'll be merging this right now
=> Check user template directory when exporting single template file in Python

CHANGELOG.md, pywal/settings.py, setup.py
=> release 3.5.0

pywal/templates/colors-alacritty.toml
Alacritty now uses toml config files instead of yml
=> Add toml config for alacritty

pywal/__main__.py
@powersda hope you don't mind that i'm opening the pr myself.
=> Added custom foreground argument

pywal/backends/okthief.py
thanks to @cakekindel
i still need to make some adjustments to have the secondary color shades.
just a question the only source right now is this: https://git.orionkindel.com/orion/okthief right? there is no package just installing from source right?
=> okthief backend

pywal/backends/colorz.py, pywal/backends/fast_colorthief.py, pywal/backends/haishoku.py, pywal/backends/modern_colorthief.py, pywal/backends/okthief.py, pywal/backends/schemer2.py, pywal/colors.py
various fixes for color adjustment, this should ensure color tones are consistent with legacy behaviour for the background color but also produce colors 7 and 8 on a bit lighter tone to be more akin to legacy while still providing a better contrast than old pywal.
=> Color adjust fix

pywal/templates/colors-zed.json
=> add zed template

pywal/__main__.py, pywal/backends/colorthief.py, pywal/backends/colorz.py, pywal/backends/fast_colorthief.py, pywal/backends/haishoku.py, pywal/backends/okthief.py, pywal/backends/schemer2.py, pywal/backends/wal.py, pywal/colors.py, pywal/export.py, pywal/image.py, pywal/reload.py, pywal/sequences.py, pywal/theme.py, pywal/util.py, pywal/wallpaper.py, setup.py
black really makes the code nice to read.
=> Formatting and typos

pywal/export.py, pywal/templates/colors.json
=> Export checksum

setup.py
This is a dirty hax
@guillaumeboehm pls tell me if this doesn't generate errors, will have to bring back the test suite after putting ou 3.7.0
=> Remove test

pywal/backends/colorthief.py, pywal/backends/colorz.py, pywal/backends/fast_colorthief.py, pywal/backends/haishoku.py, pywal/backends/modern_colorthief.py, pywal/backends/okthief.py, pywal/backends/schemer2.py, pywal/backends/wal.py, pywal/colors.py
This includes comments, docstrings and keywords in dicts.
=> Change improve formatting

pywal/wallpaper.py
@robwaz @julianmackenzie took the liberty to rebase your patches to support Mac Sonoma on here, please check if everything is correct.
=> Macos sonoma

pywal/reload.py
=> Add support for reloading waybar

pywal/reload.py
=> Add support for firefox/pywalfox

pywal/wallpaper.py
=> added hyprland support

pywal/export.py, pywal/templates/colors-wal-dwm-urg.h
@pwnxpl0it please confirm that this does work as intended with pywal16
=> dwm urgent

pywal/__main__.py, pywal/colors.py, pywal/theme.py
This makes it possible to affect the old 9 shades themes and dynamically turn them to 16 shades themes with the --cols16 flag, so long as they are in fact 9 shades themes ie: colors 1 to 7 are the same as colors 9 to 15.
=> Dynamic theme shade conversion

pywal/reload.py
=> Use pkill -USR2 to reload waybar

pywal/colorschemes/dark/dracula.json, pywal/colorschemes/dark/draculansi.json
=> Dracula colorschemes

pywal/colors.py
=> Refactor shade_16

pywal/templates/colors.fish
=> Better colors for fish shell

pywal/templates/colors-hyprland.conf
=> added a template for hyprland

pywal/wallpaper.py
I'm not sure if there's a better way, but this seems to work just fine.
=> fixed hyprland support

pywal/wallpaper.py
Most people would already have the hyprpaper daemon started on boot with their wallpapers preloaded, so all that's needed is to change the wallpaper as described [here](https://wiki.hyprland.org/Hypr-Ecosystem/hyprpaper/#ipc)
=> changing the wallpaper instead for starting the daemon

pywal/wallpaper.py
=> Actually preload the wallpaper

pywal/wallpaper.py
wbg: https://codeberg.org/dnkl/wbg
=> Add support for wbg

pywal/wallpaper.py
=> Fix the fix of the fix of hyprpaper

pywal/wallpaper.py
=> working fix for hyprpaper

pywal/wallpaper.py
=> Add support for the qdbus6 binary

CHANGELOG.md, pywal/settings.py
a new release just on this month!
=> Release 3.8.3

pywal/reload.py
you will need to start a RPC server on ```/tmp/nvim.pipe``` as mentioned [here](https://neovim.io/doc/user/starting.html#--listen) for this to work, you can also ```alias nvim=nvim --listen /tmp/nvim.pipe``` somewhere in your shellrc
=> live update nvim colorscheme

CHANGELOG.md, pywal/export.py, pywal/reload.py, pywal/settings.py, pywal/util.py
why do i even bother saying timeframes...
=> Release 3.8.5

CHANGELOG.md, pywal/settings.py
i don't like half assing things, so i'm full assing a release rn.
=> Release 3.8.6

pywal/eastereggs.py
to wayland, or not to wayland, that is the question
=> adding wayland unsupport

data/man/man1/wal.1, pywal/__main__.py, pywal/util.py
i do not know how or why this could happen, but i trust this is the solution.
fixes #162
=> Fix alpha property

data/man/man1/wal.1, pywal/__main__.py
=> Add out-dir flag

pywal/__main__.py
fixin' fixes to fixes to fix the software that needs fixing...
it is bound to eventually be fixed...
fixes #169  hopefully...
=> Fix the fix of the flag so it is fixed

CHANGELOG.md, pywal/settings.py
should have pushed this release a while ago...
oh well there's some more work to be done in pywal16 but i'd rather make this release now than delay a release just for 2 issues...
=> Release 3.8.10

pywal/backends/wal.py
we don't need colors that aren't being used anyway.
=> require just 8 colors for wal to work
